export const // eslint-disable-line one-var
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    SET_POINTS = 'SET_POINTS',
    CHANGE_POPUP = 'CHANGE_POPUP',
    CLOSE_POPUP = 'CLOSE_POPUP',
    ESTABLISH_POSTS = 'ESTABLISH_POSTS',
    ESTABLISH_TAGGED = 'ESTABLISH_TAGGED',
    CHANGE_POST_INFO = 'CHANGE_POST_INFO',
    FOLLOW_USER = 'FOLLOW_USER',
    CHANGE_UN_FOLLOW_POPUP = 'CHANGE_UN_FOLLOW_POPUP';
