export const // eslint-disable-line one-var
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    SET_POINTS = 'SET_POINTS',
    CHANGE_POPUP = 'CHANGE_POPUP',
    CLOSE_POPUP = 'CLOSE_POPUP',
    ESTABLISH_POSTS = 'ESTABLISH_POSTS',
    ESTABLISH_TAGGED = 'ESTABLISH_TAGGED',
    ADD_LIKE = 'ADD_LIKE',
    REMOVE_LIKE = 'REMOVE_LIKE',
    ADD_COMMENT = 'ADD_COMMENT';
